name: "gk-test-compose-file"
services:
  db:
      image: postgres:17.4
      container_name: postgres-db
      volumes: 
          - db-data:/var/lib/postgresql/data
      environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    image: img-spring-maven-demo
    container_name: app-spring-maven-demo
    build: .
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      env-file-property-3: ${env-file-property-3}
      env-dockerfile-property-2: ${env-dockerfile-property-2}
      env-composefile-property-1: env-composefile-val-1
    volumes: 
    - /home/gkorobkov/app/test-app-modules
    - ./api:/home/gkorobkov/app/test-app

    ports:
      - "8080:8080"

volumes:
    db-data:
        name: data-postgres-db-vlm