services:

  app:
    build: .
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_DB}:${POSTGRES_HOST}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"