services:

  app:
    build: .
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_DB}:${POSTGRES_HOST}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      env-file-property-3: ${env-file-property-3}
      env-dockerfile-property-2: ${env-dockerfile-property-2}
      env-composefile-property-1: env-composefile-val-1
      

    ports:
      - "8080:8080"